/*
 * Emits the SQL to publish the current programme + exercise catalogue.
 *
 *   node scripts/publish-program.mjs arnold6 > supabase/migrations/0004_program_v2.sql
 *   node scripts/publish-program.mjs template > supabase/migrations/0005_upper_lower.sql
 *
 * Workflow when you change the block:
 *   1. edit src/program.js
 *   2. bump PROGRAM_VERSION
 *   3. run this, paste the output into Supabase SQL Editor
 *   4. deploy the app
 *
 * Old sessions keep pointing at the old version. Nothing is rewritten.
 */
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const here = dirname(fileURLToPath(import.meta.url));
const file = process.argv[2] || "arnold6";
const src = readFileSync(join(here, `../src/programs/${file}.js`), "utf8");
const mod = await import("data:text/javascript," + encodeURIComponent(src.replace(/^export default .*$/m, "").replace(/\bexport\s+/g, "")) + "\nexport { program };");
const p = mod.program;

const EXERCISES = {};
Object.values(p.sessions).forEach((d) => d.ex.forEach((x) => { EXERCISES[x.id] = x; }));
const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";

const lines = [
  `-- Generated by scripts/publish-program.mjs`,
  `-- Programme ${p.id} version ${p.version}`,
  ``,
  `-- Exercise catalogue. Names update in place; ids never change.`,
  `insert into exercises (id, name) values`,
  Object.values(EXERCISES).map((e) => `  (${q(e.id)}, ${q(e.name)})`).join(",\n") + `\non conflict (id) do update set name = excluded.name;`,
  ``,
  `-- Programme definition. Published versions are immutable, so this only`,
  `-- inserts; re-running it is a no-op.`,
  `insert into programs (id, version, name, definition) values`,
  `  (${q(p.id)}, ${p.version}, ${q(p.name)}, ${q(JSON.stringify(p))}::jsonb)`,
  `on conflict (id, version) do nothing;`,
  ``,
];
process.stdout.write(lines.join("\n"));
